<?php

declare(strict_types=1);

namespace Escalated\Symfony\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('escalated');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->scalarNode('user_class')
                    ->defaultValue('App\\Entity\\User')
                    ->info('The fully qualified class name of the user entity.')
                ->end()
                ->scalarNode('route_prefix')
                    ->defaultValue('/support')
                    ->info('URL prefix for all Escalated routes.')
                ->end()
                ->booleanNode('ui_enabled')
                    ->defaultTrue()
                    ->info('Enable/disable the built-in Inertia UI. When disabled, only API routes and services are available.')
                ->end()
                ->booleanNode('enable_newsletters')
                    ->defaultFalse()
                    ->info('Enable/disable the newsletter HTTP routes and dispatch worker.')
                ->end()
                ->scalarNode('table_prefix')
                    ->defaultValue('escalated_')
                    ->info('Prefix for all Escalated database tables.')
                ->end()
                ->arrayNode('newsletters')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('base_url')->defaultValue('http://localhost')->end()
                        ->scalarNode('default_from')->defaultNull()->end()
                        ->scalarNode('default_reply_to')->defaultNull()->end()
                        ->scalarNode('default_theme')->defaultValue('default')->end()
                        ->integerNode('rate_limit_per_minute')->defaultValue(60)->end()
                        ->integerNode('batch_size')->defaultValue(50)->end()
                        ->booleanNode('tracking_enabled')->defaultTrue()->end()
                        ->floatNode('auto_pause_bounce_rate')->defaultValue(0.05)->end()
                        ->integerNode('auto_pause_threshold')->defaultValue(100)->end()
                        ->integerNode('claim_timeout_minutes')->defaultValue(10)->end()
                        ->scalarNode('brand_accent')->defaultValue('#2563eb')->end()
                        ->scalarNode('brand_logo_url')->defaultNull()->end()
                        ->scalarNode('brand_physical_address')->defaultNull()->end()
                    ->end()
                ->end()
                ->arrayNode('storage')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('base_url')
                            ->defaultValue('')
                            ->info('Base URL used to build attachment download links (e.g. https://cdn.example.com/attachments). When empty, a fallback route is used.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('tickets')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('allow_customer_close')
                            ->defaultTrue()
                            ->info('Whether customers can close their own tickets.')
                        ->end()
                        ->scalarNode('default_priority')
                            ->defaultValue('medium')
                            ->info('Default priority for new tickets.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('sla')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                        ->end()
                        ->booleanNode('business_hours_only')
                            ->defaultFalse()
                        ->end()
                        ->arrayNode('business_hours')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('start')->defaultValue('09:00')->end()
                                ->scalarNode('end')->defaultValue('17:00')->end()
                                ->scalarNode('timezone')->defaultValue('UTC')->end()
                                ->arrayNode('days')
                                    ->defaultValue([1, 2, 3, 4, 5])
                                    ->integerPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('ticket_actions')
                    ->info('Host-defined custom action buttons for the agent ticket screen.')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('key')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('label')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('variant')->defaultValue('secondary')->end()
                            ->booleanNode('visible')->defaultTrue()->end()
                            ->booleanNode('enabled')->defaultTrue()->end()
                            ->scalarNode('confirmation')->defaultNull()->end()
                            ->variableNode('metadata')->defaultValue([])->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('ticket_subjects')
                    ->addDefaultsIfNotSet()
                    ->info('Host-app entities a ticket can be *about* (Project, Customer, asset, …).')
                    ->children()
                        ->arrayNode('types')
                            ->info('Allowlist of subject type strings permitted via the agent/API attach endpoints.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->scalarNode('resolver')
                            ->defaultNull()
                            ->info('Service id implementing TicketSubjectResolverInterface for presentation.')
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
